import { type NextPage } from "next";
import Head from "next/head";
import { api } from "@/utils/api";
import { PageLayout } from "@/components/layout";
import { useRouter } from "next/router";

const SinglePostPage: NextPage = () => {
  const router = useRouter();
  const { query } = router;
  const { id } = query;

  const { data } = api.posts.getById.useQuery({
    id: id as string,
  });

  return (
    <>
      <Head>
        <title>Chirp 🐦</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <div className="relative flex flex-row border-b border-slate-400  p-8">
          {data?.content}
        </div>
      </PageLayout>
    </>
  );
};

export default SinglePostPage;
